name: Build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
          check-latest: true
      - run: yarn install
      - run: yarn build
      - run: yarn test --coverage --watchAll=false

      - uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          verbose: true
